/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VIEW;

import CONTROL.Controle;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JOptionPane;
import VIEW.TelaPrincipal;

/**
 *
 * @author lenon
 */
public final class Compra extends javax.swing.JFrame {

    private TelaPrincipal telaPrincipal;
    private Controle ctrl;

    /**
     * Creates new form Login
     */
    public Compra(Controle ctrl) {
        this.ctrl=ctrl;
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nome = new javax.swing.JLabel();
        nome_field = new javax.swing.JTextField();
        cpf = new javax.swing.JLabel();
        cpf_field = new javax.swing.JTextField();
        numero_cartao = new javax.swing.JLabel();
        numero_cartao_filed = new javax.swing.JTextField();
        cvs = new javax.swing.JLabel();
        cvs_field = new javax.swing.JPasswordField();
        ok_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nome.setText("Nome");

        nome_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_fieldActionPerformed(evt);
            }
        });

        cpf.setText("CPF");

        numero_cartao.setText("Número do Cartão");

        cvs.setText("CVS");

        ok_button.setText("OK");
        ok_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok_buttonMouseClicked(evt);
            }
        });
        ok_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_buttonActionPerformed(evt);
            }
        });

        jLabel1.setText("CADASTRAR CARTÃO PARA CONTINUAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nome)
                    .addComponent(nome_field, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(cpf)
                    .addComponent(cpf_field)
                    .addComponent(numero_cartao)
                    .addComponent(numero_cartao_filed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cvs)
                    .addComponent(cvs_field, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(ok_button))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nome_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cpf)
                .addGap(18, 18, 18)
                .addComponent(cpf_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero_cartao)
                    .addComponent(cvs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero_cartao_filed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cvs_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(ok_button)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ok_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ok_buttonActionPerformed

    private void nome_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_fieldActionPerformed

    private void ok_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok_buttonMouseClicked
        if (nome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Por favor, forneça o CPF", "AVISO", WIDTH);
        } else if (cpf_field.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Por favor, forneça o Nome", "AVISO", WIDTH);
        } else if (numero_cartao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Por favor, forneça o Número do Cartão", "AVISO", WIDTH);
        } else if (cvs_field.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Por favor, forneça o Número do CVS", "AVISO", WIDTH);
        } else {
            ctrl.compraRealizada();
            

            dispose();
        }
    }//GEN-LAST:event_ok_buttonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cpf;
    private javax.swing.JTextField cpf_field;
    private javax.swing.JLabel cvs;
    private javax.swing.JPasswordField cvs_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel nome;
    private javax.swing.JTextField nome_field;
    private javax.swing.JLabel numero_cartao;
    private javax.swing.JTextField numero_cartao_filed;
    private javax.swing.JButton ok_button;
    // End of variables declaration//GEN-END:variables

    public void setFrameInvisible(TelaPrincipal telaPrincipal) {
        telaPrincipal.setVisible(false);
        this.telaPrincipal = telaPrincipal;
    }

    public void setFrameVisible() {
        telaPrincipal.setVisible(true);
    }
}
